# Generated by Django 2.0.2 on 2018-03-03 20:32

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('pos_cargo', models.IntegerField(default=0)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='equipe/aluno'))),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='destaques/'))),
            ],
        ),
        migrations.CreateModel(
            name='Docente_ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('pos_cargo', models.IntegerField(default=0)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='equipe/docente_ta'))),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Img_texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='servicos/texto-img'))),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('exemplos', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(max_length=20)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='postagens/'))),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('exemplos', models.CharField(max_length=100)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='servicos/'))),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Texto_modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Servico')),
            ],
        ),
        migrations.AddField(
            model_name='img_texto',
            name='texto_modal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Texto_modal'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='post_comentado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Postagem'),
        ),
    ]
