# Generated by Django 2.0.2 on 2018-03-01 19:51

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='equipe/aluno'))),
                ('linkedin', models.CharField(max_length=20)),
                ('github', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo', models.CharField(max_length=20)),
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Docente_ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='equipe/docente_ta'))),
                ('linkedin', models.CharField(max_length=20)),
                ('github', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Img_texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='servicos/texto-img'))),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('exemplos', models.CharField(max_length=50)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='servicos/'))),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Texto_modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('servico_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Servico')),
            ],
        ),
        migrations.AlterField(
            model_name='destaque',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='destaques/')),
        ),
        migrations.AddField(
            model_name='img_texto',
            name='texto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Texto_modal'),
        ),
    ]
