# Generated by Django 2.0.2 on 2018-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180301_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.AddField(
            model_name='aluno',
            name='pos_cargo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docente_ta',
            name='pos_cargo',
            field=models.IntegerField(default=0),
        ),
    ]
