# Generated by Django 2.0.2 on 2018-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180305_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.CharField(default='oi', max_length=50),
        ),
    ]
