# Generated by Django 2.0.2 on 2018-03-06 17:26

from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180306_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tipo_cargo', models.CharField(choices=[('1', 'doscente'), ('2', 'discente')], max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('pos_cargo', models.IntegerField()),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='equipe/aluno'))),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Docente_ta',
        ),
    ]
