# Generated by Django 2.0.2 on 2018-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180306_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='pos_cargo',
            field=models.IntegerField(choices=[(1, 'Coordenador'), (2, 'Presidente'), (3, 'Diretor de Projetos')]),
        ),
    ]
