# Generated by Django 2.0.2 on 2018-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180306_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='cargo',
            field=models.CharField(choices=[('1', 'Coordenador'), ('2', 'Presidente'), ('3', 'Diretor de Projetos'), ('4', 'Diretor de Negócios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='pos_cargo',
            field=models.IntegerField(choices=[(1, 'Coordenador'), (2, 'Presidente'), (3, 'Diretor de Projetos'), (4, 'Diretor de Negócios')]),
        ),
    ]
