# Generated by Django 2.0.2 on 2018-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180306_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='tipo_cargo',
            field=models.CharField(choices=[('Doscente', 'Doscente'), ('Discente', 'Discente')], max_length=20),
        ),
    ]
