# Generated by Django 2.0.2 on 2018-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180306_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='cargo',
            field=models.CharField(choices=[('Coordenador', 'Coordenador'), ('Presidente', 'Presidente'), ('Diretor de Projetos', 'Diretor de Projetos'), ('Diretor de Negócios', 'Diretor de Negócios')], max_length=20),
        ),
    ]
