# Generated by Django 2.0.2 on 2018-03-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180306_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='sobre',
            field=models.TextField(default='oi'),
        ),
    ]
