# Generated by Django 2.0.2 on 2018-03-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180306_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipe'),
        ),
    ]
