# Generated by Django 2.0.2 on 2018-03-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180306_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='categoria',
            field=models.CharField(default='oi', max_length=50, verbose_name='Categoria'),
        ),
    ]
