# Generated by Django 2.0.2 on 2018-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180307_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='cargo',
            field=models.CharField(choices=[('Coordenador', 'Coordenador'), ('Diretor Presidente', 'Diretor Presidente'), ('Diretor Vice-Presidente', 'Diretor Vice-Presidente'), ('Diretor de Projetos', 'Diretor de Projetos'), ('Diretor de Processos Internos', 'Diretor de Processos Internos'), ('Diretor de Negócios', 'Diretor de Negócios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='pos_cargo',
            field=models.IntegerField(choices=[(1, 'Coordenador'), (2, 'Diretor Presidente'), (3, 'Diretor Vice-Presidente'), (4, 'Diretor de Projetos'), (5, 'Diretor de Processos Internos'), (6, 'Diretor de Negócios')]),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='tipo_cargo',
            field=models.CharField(choices=[('Docente', 'Docente'), ('Discente', 'Discente')], max_length=20),
        ),
    ]
